### ISSUE TITLE
Warning: Cannot update during an existing state transition (such as within `render`).

### ISSUE THREAD

**Issue by Vanillabacke** [bartaxyz/react-tree-list#14]
I get following warning when I am using your example code:
```Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.```

You can get rid of it, by removing the logic of triggerOnChange in 'ReactTreeList.tsx' line 224:
```
...
 if (triggerOnChange) {
      onChange([...data]); // this line is causing the warning
}
...
```

I couldn't see any difference with / without this logic.
I guess the logic was to trigger the onChange event just once after the order was changed (https://github.com/bartaxyz/react-tree-list/issues/13)? 

Cheers!

**Comment by bartaxyz** [comment]
Thank you for this bug report!

I refactored the component a bit in the following PR: https://github.com/bartaxyz/react-tree-list/pull/16

This should make sure the `onChange` will be triggered only after the component is rendered. This way it shouldn't interfere with the current render.
