### ISSUE TITLE
How to get selected item and control the styles of background color

### ISSUE THREAD

**Issue by zhangwei900808** [bartaxyz/react-tree-list#17]
Thanks!!! very good tree component

I want to get selected item and set choosed item background color

**Comment by bartaxyz** [comment]
Hello and thank you! 🙂 

This library has been somewhat abandoned for some time now. I haven't had time to put more effort into this. It's certainly great to see it receiving attention. I've just published v0.1.0 of this library, where you can adjust colors and some styles. It's not full customization though.

You can now upgrade the library to version "0.1.0" and use the `itemOptions` property to pass the colors:

```tsx
itemOptions={{
  focusedOutlineColor: "rgba(255, 0, 0, 0.5)",
  focusedOutlineWidth: 1,
  focusedBorderRadius: 50,
  focusedBackgroundColor: "rgba(255, 0, 0, 0.1)",
}}
```

Or see the storybook example: https://bartaxyz.github.io/react-tree-list/?path=/story/tree-list--with-custom-styles

**Comment by zhangwei900808** [comment]
@bartaxyz but the library is very good and I want to choosed item and get item data if you not time I can try it THKS!

**Comment by zhangwei900808** [comment]
@bartaxyz Hi! I had two feture in this library Please push new version
