### ISSUE TITLE
Newly added item is not reactive

### ISSUE THREAD

**Issue by chenstarx** [bartaxyz/react-tree-list#28]
Hi, I found that if I add a new item into the `data` list, the new item is not reactive, I can not move it to any other location. The `onDrop` event was also not triggered after I dragged the new item. The old existed item works fine.

For more detail please have a look at:
https://codesandbox.io/s/intelligent-lake-3x8pu6?file=/src/Component.js

**Comment by chenstarx** [comment]
Solved after changing id's type from Number to String

**Comment by bartaxyz** [comment]
Hello @chenstarx. Thanks so much for reporting!

I'll see what we can do about either better documentation or implementing support for numeric `id`s.

**Comment by bartaxyz** [comment]
After browsing around the code, I decided it doesn't make much sense to allow numerical values. It's better to have a simply typed API. For as long as it's documented well, it should be alright.

I made a [pull request](https://github.com/bartaxyz/react-tree-list/pull/29) that updates the README and a comment that urges to use strings. Thank you for reporting!
