### ISSUE TITLE
Implement selectable items

### ISSUE THREAD

**Issue by bartaxyz** [bartaxyz/react-tree-list#6]

**Comment by zhangwei900808** [comment]
nice Work!
when publish ?

**Comment by bartaxyz** [comment]
Thanks to @zhangwei900808 - https://github.com/bartaxyz/react-tree-list/pull/21, I believe I can close this issue.

Available in v0.2.0 of the package
https://github.com/bartaxyz/react-tree-list/releases/tag/v0.2.0-alpha.1
